name: unit testing workflow
on:  
  push:
    branches:
      - main
      - 'feature/*'
env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: ${{vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
  unit-testing:
    runs-on: ubuntu-latest
    steps:
      - name: download repos
        uses: actions/checkout@v4

      - name: setup node JS version 
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: node package manager install
        run: npm install

      - name: unit testing 
        run: npm test

      - name: Archieve test results
        uses: actions/upload-artifact@v4
        with:
          name: Unit-Testing results
          path: unit-testing-results.xml


      

